version: "3.8"
services:
    FrontEnd:
        container_name: PaginaWeb
        restart: always
        build: ./
        image: angular-web
        ports: 
            - "80:4200"
        logging: 
            driver: none